{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blue-kakapo.serviceAccountName" . }}
  labels: {{- include "blue-kakapo.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
